plugins:
  - rubocop-performance

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "pkg/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "test/**/*.rb"

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Style/ClassAndModuleChildren:
  Exclude:
    - "test/**/*.rb"

Style/GuardClause:
  Exclude:
    - "test/**/*.rb"
